version: "3.3"

services:
  backend-api:
    # location of dockerfile
    build: ./backend
    # restart on crash
    restart: always
    # working directory
    working_dir: /usr/src/app
    # startup cmd
    command: bash -c "yarn run dev"
    # volume map
    volumes:
      - ./backend:/usr/src/app
    # port map
    ports:
      - 8000:8000
    # shared network
    networks:
      - api

  frontend-app:
    stdin_open: true
    build: ./frontend
    restart: always
    # working directory in container to place files
    working_dir: /usr/src/app
    # startup command if it takes a long time uncomment line 51 and comment line 50, if you do this
    #   you must run `yarn` at the package.json level locally prior to starting
    # command: bash -c "yarn && yarn start"
    command: bash -c "yarn start"
    # map code volumes from local to inside working directory, changes made locally will update into the container
    volumes:
      - ./frontend:/usr/src/app
    # specify dependency on mysql db
    depends_on:
      - backend-api
    # ports to map, YOU CANNOT RUN ANYTHING ELSE ON PORT 3000
    ports:
      - 3000:3000
    # shared network
    networks:
      - api

# specify networks
networks:
  api:
